#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/Users/gregglickert/opt/anaconda3/envs/NeuroLab/lib/python3.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/Users/gregglickert/opt/anaconda3/envs/neurolab/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/gregglickert/Documents/GitHub/LargeScaleBLA/tuning/Gregs Stuff/x86_64/.libs/libnrnmech.so" "$@"
